### ISSUE TITLE
error loading forum content

### ISSUE THREAD

**Issue by saturnflyer** [saturnflyer/purple_door#53]
The forum 1) isn't loading assets properly and 2) seems to be blowing up in the view looking for an object called `thredded`

Here's the stack trace:

```
 [2015-08-03T21:13:45.913200 #173]  INFO -- : Started GET "/forum/messageboards/new" for 184.173.166.154 at 2015-08-03 21:13:45 +0000
2015-08-03T21:13:45.922828+00:00 app[web.1]: I, [2015-08-03T21:13:45.922504 #173]  INFO -- : Processing by Thredded::MessageboardsController#new as HTML
2015-08-03T21:13:45.948716+00:00 app[web.1]: F, [2015-08-03T21:13:45.948406 #173] FATAL -- :
2015-08-03T21:13:45.948723+00:00 app[web.1]: NameError (undefined local variable or method `thredded' for #<Thredded::MessageboardsController:0x007f481ff7fa30>):
2015-08-03T21:13:45.948734+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/bundler/gems/thredded-39da38c744ab/app/controllers/thredded/application_controller.rb:19:in `block in <class:ApplicationController>'
2015-08-03T21:13:45.948736+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/rescuable.rb:114:in `instance_exec'
2015-08-03T21:13:45.948737+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/rescuable.rb:114:in `block in handler_for_rescue'
2015-08-03T21:13:45.948740+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/rescuable.rb:80:in `rescue_with_handler'
2015-08-03T21:13:45.948739+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/rescuable.rb:80:in `call'
2015-08-03T21:13:45.948742+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:15:in `rescue_with_handler'
2015-08-03T21:13:45.948743+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:32:in `rescue in process_action'
2015-08-03T21:13:45.948745+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
2015-08-03T21:13:45.948746+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
2015-08-03T21:13:45.948748+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
2015-08-03T21:13:45.948749+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2015-08-03T21:13:45.948753+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
2015-08-03T21:13:45.948755+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2015-08-03T21:13:45.948756+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
2015-08-03T21:13:45.948757+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
2015-08-03T21:13:45.948759+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
2015-08-03T21:13:45.948760+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
2015-08-03T21:13:45.948764+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in `dispatch'
2015-08-03T21:13:45.948765+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
2015-08-03T21:13:45.948767+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in `block in action'
2015-08-03T21:13:45.948770+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `call'
2015-08-03T21:13:45.948771+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
2015-08-03T21:13:45.948775+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in `serve'
2015-08-03T21:13:45.948778+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2015-08-03T21:13:45.948781+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
2015-08-03T21:13:45.948803+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
2015-08-03T21:13:45.948807+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
2015-08-03T21:13:45.948810+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
2015-08-03T21:13:45.948814+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `public_send'
2015-08-03T21:13:45.948817+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `method_missing'
2015-08-03T21:13:45.948821+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/mapper.rb:51:in `serve'
2015-08-03T21:13:45.948827+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
2015-08-03T21:13:45.948824+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2015-08-03T21:13:45.948831+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
2015-08-03T21:13:45.948834+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
2015-08-03T21:13:45.948838+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
2015-08-03T21:13:45.948841+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
2015-08-03T21:13:45.948845+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
2015-08-03T21:13:45.948848+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
2015-08-03T21:13:45.948852+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
2015-08-03T21:13:45.948856+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
2015-08-03T21:13:45.948863+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260:in `call'
2015-08-03T21:13:45.939284+00:00 app[web.1]: I, [2015-08-03T21:13:45.936906 #173]  INFO -- : Completed 500 Internal Server Error in 14ms (ActiveRecord: 0.0ms)
2015-08-03T21:13:45.948859+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2015-08-03T21:13:45.920864+00:00 app[web.1]: D, [2015-08-03T21:13:45.920467 #173] DEBUG -- :   SQL (2.4ms)  SELECT  "users"."id" AS t0_r0, "users"."email" AS t0_r1, "users"."encrypted_password" AS t0_r2, "users"."reset_password_token" AS t0_r3, "users"."reset_password_sent_at" AS t0_r4, "users"."remember_created_at" AS t0_r5, "users"."sign_in_count" AS t0_r6, "users"."current_sign_in_at" AS t0_r7, "users"."last_sign_in_at" AS t0_r8, "users"."current_sign_in_ip" AS t0_r9, "users"."last_sign_in_ip" AS t0_r10, "users"."created_at" AS t0_r11, "users"."updated_at" AS t0_r12, "users"."permissions" AS t0_r13, "users"."superuser" AS t0_r14, "users"."first_name" AS t0_r15, "users"."last_name" AS t0_r16, "users"."birthdate" AS t0_r17, "users"."profile_image" AS t0_r18, "thredded_user_preferences"."id" AS t1_r0, "thredded_user_preferences"."user_id" AS t1_r1, "thredded_user_preferences"."time_zone" AS t1_r2, "thredded_user_preferences"."created_at" AS t1_r3, "thredded_user_preferences"."updated_at" AS t1_r4, "thredded_user_details"."id" AS t2_r0, "thredded_user_details"."user_id" AS t2_r1, "thredded_user_details"."latest_activity_at" AS t2_r2, "thredded_user_details"."posts_count" AS t2_r3, "thredded_user_details"."topics_count" AS t2_r4, "thredded_user_details"."superadmin" AS t2_r5, "thredded_user_details"."created_at" AS t2_r6, "thredded_user_details"."updated_at" AS t2_r7 FROM "users" LEFT OUTER JOIN "thredded_user_preferences" ON "thredded_user_preferences"."user_id" = "users"."id" LEFT OUTER JOIN "thredded_user_details" ON "thredded_user_details"."user_id" = "users"."id" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 2]]
2015-08-03T21:13:45.948866+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
2015-08-03T21:13:45.948869+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
2015-08-03T21:13:45.948883+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2015-08-03T21:13:45.948881+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
2015-08-03T21:13:45.948911+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
2015-08-03T21:13:45.948913+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2015-08-03T21:13:45.948873+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'
2015-08-03T21:13:45.948877+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in `call'
2015-08-03T21:13:45.948914+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
2015-08-03T21:13:45.948916+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2015-08-03T21:13:45.948920+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2015-08-03T21:13:45.948921+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
2015-08-03T21:13:45.948922+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
2015-08-03T21:13:45.948944+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
2015-08-03T21:13:45.948942+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2015-08-03T21:13:45.948945+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
2015-08-03T21:13:45.948947+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
2015-08-03T21:13:45.948950+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2015-08-03T21:13:45.948952+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
2015-08-03T21:13:45.948960+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2015-08-03T21:13:45.948956+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
2015-08-03T21:13:45.948967+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
2015-08-03T21:13:45.948963+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in `call'
2015-08-03T21:13:45.948970+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
2015-08-03T21:13:45.948974+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
2015-08-03T21:13:45.948977+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/passenger-5.0.15/lib/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
2015-08-03T21:13:45.948981+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/passenger-5.0.15/lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
2015-08-03T21:13:45.948984+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/passenger-5.0.15/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
2015-08-03T21:13:45.948988+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/passenger-5.0.15/lib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
2015-08-03T21:13:45.948991+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/passenger-5.0.15/lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
2015-08-03T21:13:45.948995+00:00 app[web.1]:
2015-08-03T21:13:45.948998+00:00 app[web.1]:
```

@jayroh anything come to mind here?

**Comment by jcavena** [comment]
Could the gem caching be causing this?

**Comment by jayroh** [comment]
I think this had to do with the path helpers being sent to a `thredded` object that didn't exist in this instance. @saturnflyer this was fixed by your pull request over here: https://github.com/jayroh/thredded/pull/124

Just tried everything out with upstream/master and it looks like it's ok.
